### ISSUE TITLE
/in no longer emits metadata

### ISSUE THREAD

**Issue by vito** [concourse/bosh-io-stemcell-resource#11]
This used to emit `sha` and `url` fields:

![screenshot from 2016-09-21 15-17-43](https://cloud.githubusercontent.com/assets/1880/18731068/92d3c6fc-800e-11e6-8eb8-43f3f65788db.png)

/cc @zachgersh

**Comment by zachgersh** [comment]
closed via 0dc6a5d11a218b236ce51a9ef70e38110a9daba9 - committed as the wrong user but who cares.
