### ISSUE TITLE
Aggressively retry downloads

### ISSUE THREAD

**Issue by vito** [concourse/bosh-io-stemcell-resource#13]
https://ci.concourse.ci/teams/main/pipelines/main/jobs/bosh-testflight/builds/546 failed:

![screenshot from 2016-09-23 14-47-11](https://cloud.githubusercontent.com/assets/1880/18802259/a2328202-819c-11e6-84d0-6491cf136511.png)

**Comment by zachgersh** [comment]
@vito can do - saw this and was intrigued that it even happened.

**Comment by zachgersh** [comment]
Was waiting to accumulate at least two issues before I started work again.

**Comment by zachgersh** [comment]
@vito one half (retry failed http, like connection timeout is done).

https://github.com/concourse/bosh-io-stemcell-resource/commit/41250ed77e5f0cada1793d8928e34ed856d55785

`io.EOF` check coming next.

**Comment by zachgersh** [comment]
@vito fixed for both retryable http errors and unexpect EOFs (a bit more than what you asked but nice nonetheless).

**Comment by ljfranklin** [comment]
@zachgersh I have the perfect test for this feature. We have a Concourse worker in China that has to download a 500MB stemcell from bosh.io. Even when using the CloudFront URL, it just failed 5 times in a row with "TLS handshake timeout", then "read: connection timed out", followed by a few "read: connection reset by peer". Hopefully these fall under "Temporary" errors.

Gonna build a Docker image from master and put the retries through their paces :)

**Comment by zachgersh** [comment]
Yesssss! Please reopen if you find it doesn't actually work. This will
retry infinitely so be prepared to kill the task as needed!

**Comment by ljfranklin** [comment]
@zachgersh so we should probably re-open this. All the download attempts failed with "request canceled (Client.Timeout exceeded while reading body)". The 5 minute timeout [here](https://github.com/concourse/bosh-io-stemcell-resource/blob/38e5bd36fc226ece5ef15832149aded31c0a9a5c/cmd/in/main.go#L60) is way too low for the China download unfortunately. I'm trying it again with the Timeout set to 0. Any specific reason the 5 minute timeout was introduced? The [DefaultTransport](https://golang.org/src/net/http/transport.go) would still give some lower-level handshake and idle connection timeouts, so the connection shouldn't hang forever even if the HTTP Client Timeout is 0.

**Comment by zachgersh** [comment]
@ljfranklin - can we open a new issue to remove that timeout?  I can totally get rid of it now that I introduced a different fake :/
