### ISSUE TITLE
Versions returned out of order

### ISSUE THREAD

**Issue by vito** [concourse/bosh-io-stemcell-resource#14]
![screenshot from 2016-10-21 12-30-18](https://cloud.githubusercontent.com/assets/1880/19609123/2a76c698-978a-11e6-8ed5-2881e285ec76.png)

Not sure if this should simply be reversed or if bosh.io even provides any guarantees around ordering.

**Comment by zachgersh** [comment]
@vito I thought I was ordering these :/

@davewalter also reported this.

GODDAMNIT

**Comment by ljfranklin** [comment]
@vito @zachgersh yeah, we just hit this too. Not sure about the ordering, but we did notice `check` returns duplicates. Quick and dirty patch:

``` diff
diff --git a/versions/versions.go b/versions/versions.go
index 42428b6..b3d1181 100644
--- a/versions/versions.go
+++ b/versions/versions.go
@@ -34,7 +34,7 @@ func (f Filter) Versions() ([]List, error) {
            panic(err)
        }

-       r, err := semver.ParseRange(fmt.Sprintf(">=%s", parsedVersion.String()))
+       r, err := semver.ParseRange(fmt.Sprintf(">%s", parsedVersion.String()))
        if err != nil {
            panic(err)
        }

```

**Comment by zachgersh** [comment]
hey @ljfranklin I am now consistently sorting the versions. I actually haven't seen the duplicate issue. Removing the `=` would break the concourse contract which is

from implementing a resource:

> print the array of new versions, in chronological order, to stdout, including the requested version if it's still valid.

**Comment by zachgersh** [comment]
@vito so, my acceptance test for check never failed (which is a little disconcerting).  If bosh.io wasn't guaranteeing order wouldn't we expect to see the test randomly fail (maybe the test isn't run consistently enough to get back a random order).  The resource now guarantees the order either way.

**Comment by ljfranklin** [comment]
@zachgersh good call, I'm guessing the duplicates were just a side effect of the ordering bug, e.g. check returns 3263 as latest, then 3262 as latest due to bad ordering, then 3263 again. Definitely weird, the bosh.io API seems to be sorting stemcells correctly right now. Maybe ordering is not always guaranteed? cc @cppforlife out of curiosity.

**Comment by zachgersh** [comment]
@ljfranklin yeah, I really don't understand why this would happen as my acceptance tests rely on ordering and it has NEVER failed. I thought it had something to do with version pinning but that doesn't seem plausible either.

I am really hoping this fixes it and will probably build a custom stemcell resource just to test that this sorting does maintain order now in our releng pipelines.

**Comment by vito** [comment]
This isn't fixed; it needs to return them in chronological (i.e. increasing) order. This was probably also the cause for them appearing out of order in the UI.
